version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gen-phpmyadmin-cloud
    restart: always
    env_file: .env
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:80"
